### ISSUE TITLE
proc.cmd does not include arguments on Windows

### ISSUE THREAD

**Issue by ronkorving** [sindresorhus/ps-list#10]
On Windows, I only see `proc.cmd` show executable file names, not arguments. For example, when running:

```sh
node ./foo/bar.js
```

I only see `node.exe`.

**Comment by kevva** [comment]
The `tasklist` command only shows the image name, not the arguments it was invoked with.

**Comment by ronkorving** [comment]
Right. So, if it's really impossible to implement, I think the readme should mention it. It currently already mentions:

> The cpu percentage is not supported on Windows.

But it doesn't mention this issue.

**Comment by kevva** [comment]
Sure, a PR would be welcome.

**Comment by sindresorhus** [comment]
The `.cmd` property was removed on Windows in v6.
