### ISSUE TITLE
Add memory property in the processes

### ISSUE THREAD

**Issue by taylorroos** [sindresorhus/ps-list#11]
Now:
`{pid: 3213, name: 'node', cmd: 'node test.js', cpu: '0.1'}`

After:
`{pid: 3213, name: 'node', cmd: 'node test.js', cpu: '0.1', mem: '1.5'}`

**Comment by sindresorhus** [comment]
Sure. PR welcome. Should be `mem` => `memory`.

**Comment by sindresorhus** [comment]
Fixed by #12
