### ISSUE TITLE
Extremely slow performance on windows

### ISSUE THREAD

**Issue by mceachen** [sindresorhus/ps-list#18]
Moved issue from [process-exists](https://github.com/sindresorhus/process-exists/issues/6):

```
$ time node -e 'require("ps-list")().then(arr => console.log("found " + arr.length + " procs"))'
found 226 procs

real    0m4.964s
user    0m0.016s
sys     0m0.000s
```

Note that `tasklist` on this machine takes ~1/5 of a second:

```
$ time tasklist | wc -l
225

real    0m0.262s
user    0m0.000s
sys     0m0.062s
```

System information:
* Windows 10 Pro Version 10.0.17134 Build 17134
* node v8.11.3

**Comment by mceachen** [comment]
I've opened a PR on tasklist that resolves this issue.

**Comment by sindresorhus** [comment]
Closing as the tasklist PR was merged and released.
