### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ljubic** [sindresorhus/ps-list#22]
I wanted to check this library out, but after using the example code you provided I am getting the following error:
` TypeError: Cannot read property 'trim' of undefined`

I have node v10 installed and using it on MacOS Mojave.

**Comment by sindresorhus** [comment]
Are you running the latest v10 version? If not I would try upgrading to the latest first.

**Comment by ljubic** [comment]
Yes, I have v10.12.0 installed.

**Comment by sindresorhus** [comment]
Hmm, it must be failing at https://github.com/sindresorhus/ps-list/blob/45a45d882040f76aa3eb10f67893fc9e430b26bc/index.js#L36

Can you add `console.log(stdout);` on line 32 and share the output?

**Comment by ljubic** [comment]
I already tried that, and stdout is _undefined_.

**Comment by ljubic** [comment]
I tested with removing brackets around stdout and now it works:
```javascript
const stdout = await execFile('ps', [flags, `pid,${cmd}`], {maxBuffer: TEN_MEGABYTES});
```

**Comment by ljubic** [comment]
@sindresorhus Can I make the pull request for this? Want to make my first open source contribution. Can you just test it on Windows so I can know whether the corresponding windows function should be changed as well. Looking at previous commits, I would assume yes :)

**Comment by sindresorhus** [comment]
Are you sure you're actually running the correct version? Try console logging `process.versions`.

From Node.js docs:

> If this method is invoked as its util.promisify()ed version, it returns a Promise for an Object with stdout and stderr properties. In case of an error (including any error resulting in an exit code other than 0), a rejected promise is returned, with the same error object given in the callback, but with an additional two properties stdout and stderr. - https://nodejs.org/dist/latest-v10.x/docs/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

**Comment by ljubic** [comment]
Executing
```javascript
  const { execFile } = require('child_process');
      const child = execFile('node', ['--version'], (error, stdout, stderr) => {
        if (error) {
          throw error;
        }
        console.log("version", stdout);
      });
```

gives the same node version v10.12.0 .

**Comment by ljubic** [comment]
I am using this boilerplate for electron app:
[https://github.com/electron-react-boilerplate/electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

Could there in project settings be some defined option to use other node version? I see in travis.yml file that they specified node_js version 9, but I am not sure whether that have influence on it.

**Comment by sindresorhus** [comment]
So when you run the snippet, you run it in Electron and not pure Node.js? If so, it could be an Electron bug.

**Comment by ljubic** [comment]
Yes, in Electron.

**Comment by ljubic** [comment]
@sindresorhus could the problem be that this boilerplate is using Electron 2.0.6? [Electron 2.0.0 ](https://electronjs.org/releases#2.0.0) uses Node 8.6 and in Version they switch to v10.2.0.

**Comment by sindresorhus** [comment]
Could be, yes.

**Comment by ljubic** [comment]
@sindresorhus is there any way to check whether the process has opened (not active) window? I am also using your active-win package, but need to get list of opened windows :)

**Comment by sindresorhus** [comment]
Maybe https://github.com/sentialx/node-window-manager
