### ISSUE TITLE
Cannot find module 'ps-list' when in electron and packed on Windows

### ISSUE THREAD

**Issue by bruno-robert** [sindresorhus/ps-list#34]
I'm trying to integrate ps-list into an electron app that is then packaged using electron-builder.

Everything works fine on mac (both in development and packaged), things start to break only when I try to package the app on windows. Running the .exe will immediately trigger a "Cannot find module 'ps-list'" error.

I've tried excluding ps-list from the asar archive but it's still doesn't work. 
```
"asar": true,
"asarUnpack": [
    "node_modules/ps-list/**/*"
],
```
When I disable asar completely everything works...

I've done a bit of digging into the code and my guess is the issue comes from the fact ps-list needs to run an executable (only on windows). To do so the executable must be outside the app.asar archive. But since ps-list uses __dirname to get the directory containing the executable, it's still looking at the app.asar/ directory instead of app.asar.unpacked/.

**Comment by sindresorhus** [comment]
This is not the place to ask for Electron help.

**Comment by xmsz-stu** [comment]
any sulotion?
