### ISSUE TITLE
Invalid regular expression error in node v8.10.0

### ISSUE THREAD

**Issue by pavanyekabote** [sindresorhus/ps-list#48]
In node v8.10.0, it is throwing error for the following line itself.
```
let pslist = require('ps-list')
```

Error is : **SyntaxError: Invalid regular expression: /^[ \t]*(?<pid>\d+)[ \t]+(?<ppid>\d+)[ \t]+(?<uid>\d+)[ \t]+(?<cpu>\d+\.\d+)[ \t]+(?<memory>\d+\.\d+)[ \t]+/: Invalid group**

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ps-list/blob/6ba1dc7425fc4014e4c061a11d9c7dee16999239/package.json#L13-L15
