### ISSUE TITLE
the library doesn't work when I publish app to appstore

### ISSUE THREAD

**Issue by thanhnvpk01168** [sindresorhus/ps-list#52]
i get error like this 
{errno:"EPERM", code:"EPERM", syscall:"spawn"}

Everything works perfectly as I have not published my app to the appstore.
After I publish to appstore it doesn't work and shows like above error.
can you take a look for me, i don't know what is the cause, i'm using electrons.

thanks in advance.

**Comment by sindresorhus** [comment]
The App Store, or rather sandboxing, has restrictions on what can be spawned. This has really nothing to do with this package, and this package is made to work with Node.js. With any other usage, you're on your own to figure it out.
