### ISSUE TITLE
CommonJS modules

### ISSUE THREAD

**Issue by Glebkiselev11** [sindresorhus/ps-list#56]
Hi, do you plan to add support for CommonJS modules import?

**Comment by sindresorhus** [comment]
No: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by prohetamine** [comment]
It's so stupid to stand your ground and impose new standards on people... Am I against it ? No! But what should I do if out of all the modules that I have in the project, electron conflicts if I use commonjs, and if I use module, I get an error from your "ps-list" package, do you know what to do? If you love ESM so much, then you should do Electron and the rest of the popular solutions first, I'm sad that I can't use your software, I'm almost your fan -_-

**Comment by apss-pohl** [comment]
> It's so stupid to stand your ground and impose new standards on people... Am I against it ? No! But what should I do if out of all the modules that I have in the project, electron conflicts if I use commonjs, and if I use module, I get an error from your "ps-list" package, do you know what to do? If you love ESM so much, then you should do Electron and the rest of the popular solutions first, I'm sad that I can't use your software, I'm almost your fan -_-

Did you somehow work around this? Just stumbled over the same situation with electron and vite as bundler.
