### ISSUE TITLE
Unable to use ESM modules on Electron

### ISSUE THREAD

**Issue by seahindeniz** [sindresorhus/ps-list#57]
Hello, Electron doesn't support ESM modules yet and the issue is still open https://github.com/electron/electron/issues/21457.
Do you plan using a bundler (Vite, etc.) to build and release multiple types?

If you accept PR, I could give a hand 🤚

**Comment by seahindeniz** [comment]
No, I meant using a bundler for this library. Even using a bundler on a project, doesn't solve the problem with ESM module

**Comment by Stoyvo** [comment]
This issue should be open. It's a very valid issue that is specific to the project. Other imports are fine, it's often up to the package to support various targets.

@seahindeniz how did you get around this?

**Comment by seahindeniz** [comment]
I couldn't find a solution to this lib however, I just found out this library https://github.com/heyikang/ps-list. Maybe it could help
