### ISSUE TITLE
Return the ppid

### ISSUE THREAD

**Issue by axetroy** [sindresorhus/ps-list#9]
like it said

**Comment by sindresorhus** [comment]
Looks like it should be possible to get it with `ps`: https://www.google.no/search?q=ps+ppid&oq=ps+ppid

**Comment by DominguesGM** [comment]
Would it be important to get the ppid in windows systems or would Linux be enough?  I've made the changes necessary to get the ppid on linux, but as far as I'm aware the _tasklist_ command doesn't provide a way to retrieve ppid.

If it's only for linux, I'm ready to do a pull request.

**Comment by sindresorhus** [comment]
Yeah, sure. Just make sure you mark it as Linux-only in the docs.

**Comment by DominguesGM** [comment]
@sindresorhus Sorry for the duplicate PR's, had some issues squashing the commits of the one which was failing the build and decided to close it to start a clean one.
